apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-new-user-sa-cluster-admin-binding
subjects:
- kind: ServiceAccount
  name: my-new-user-sa
  namespace: my-new-namespace
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io